// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portiere-ui/CommandCenter.tsx": () => import("../components/mockups/portiere-ui/CommandCenter.tsx"),
  "./components/mockups/portiere-ui/TerminalPro.tsx": () => import("../components/mockups/portiere-ui/TerminalPro.tsx")
};
